#ifndef TIMER_CONFIG_H
#define TIMER_CONFIG_H

// ***************************************************** TIMER 0 **********************************************************
#define TIMER0_ENABLE ENABLE
#if TIMER0_ENABLE == ENABLE
#define TIMER0_WAVEFORM WAVEFORM_FASTPWM
#define TIMER0_PRESCALER PRESCALER_8
/*
-> IF YOU CHOOSE WAVEFORM = WAVEFORM_NORMAL
-TIMER0_OC0_CANCELD

-> IF YOU CHOOSE WAVEFORM = WAVEFORM_CTC
OC0_BEHAVIOR Options:
-TIMER0_OC0_TOOGLE_ON_CTC
-TIMER0_OC0_CLR_ON_CTC
-TIMER0_OC0_SET_ON_CTC
-TIMER0_OC0_CANCELD

-> IF YOU CHOOSE WAVEFORM = WAVEFORM_FASTPWM
OC0_BEHAVIOR Options:
-TIMER0_OC0_CLR_ON_CTC
-TIMER0_OC0_SET_ON_CTC
-TIMER0_OC0_RESERVED
-TIMER0_OC0_CANCELD

-> IF YOU CHOOSE WAVEFORM = WAVEFORM_PWMPHASECORRECT
OC0_BEHAVIOR Options:
-TIMER0_OC0_CLR_ON_CTC
-TIMER0_OC0_SET_ON_CTC
-TIMER0_OC0_RESERVED
-TIMER0_OC0_CANCELD
*/
#define TIMER0_OC0_BEHAVIOR TIMER0_OC0_CLR_ON_CTC

#else
//
#endif

// ***************************************************** TIMER 1 **********************************************************
#define TIMER1_ENABLE DISABLE
#if TIMER1_ENABLE == ENABLE
/*
Options for TIMER1_WAVEFORM:
- NORMAL
- PWM_PHASECORRECT_8BIT
- PWM_PHASECORRECT_9BIT
- PWM_PHASECORRECT_10BIT
- CTC_OCR1A
- FASTPWM_8BIT
- FASTPWM_9BIT
- FASTPWM_10BIT
- PWM_PHASEFREQCORRECT_ICR
- PWM_PHASEFREQCORRECT_OCR1A
- PWM_PHASECORRECT_ICR
- PWM_PHASECORRECT_OCR1A
- CTC_ICR
- RESERVED
- FASTPWM_ICR
- FASTPWM_OCR1A
*/
#define TIMER1_WAVEFORM FASTPWM_ICR

#define TIMER1_PRESCALER PRESCALER_8

/*

(((((((((((((((((x = A , B)))))))))))))))))

-> IF YOU CHOOSE WAVEFORM = NORMAL
-TIMER1_OC1x_CANCELD

-> IF YOU CHOOSE WAVEFORM = CTC
OC1x_BEHAVIOR Options:
-TIMER1_OC1x_TOOGLE_ON_CTC
-TIMER1_OC1x_CLR_ON_CTC
-TIMER1_OC1x_SET_ON_CTC

-> IF YOU CHOOSE WAVEFORM = FASTPWM
OC1x_BEHAVIOR Options:
-TIMER1_OC1x_CLR_ON_CTC
-TIMER1_OC1x_SET_ON_CTC


-> IF YOU CHOOSE WAVEFORM = PWMPHASECORRECT
OC1x_BEHAVIOR Options:
-TIMER1_OC1x_CLR_ON_CTC
-TIMER1_OC1x_SET_ON_CTC

*/
#define TIMER1_OC1A_BEHAVIOR TIMER1_OC1A_CLR_ON_CTC
#define TIMER1_OC1B_BEHAVIOR TIMER1_OC1B_CANCELD

#else
//
#endif

// ***************************************************** TIMER 2 **********************************************************
#define TIMER2_ENABLE DISABLE
#if (TIMER2_ENABLE == ENABLE)
#define TIMER2_WAVEFORM WAVEFORM_NORMAL
#define TIMER2_PRESCALER PRESCALER_1
/*
-> IF YOU CHOOSE WAVEFORM = WAVEFORM_NORMAL
-TIMER2_OC2_CANCELD

-> IF YOU CHOOSE WAVEFORM = WAVEFORM_CTC
OC0_BEHAVIOR Options:
-TIMER2_OC2_TOOGLE_ON_CTC
-TIMER2_OC2_CLR_ON_CTC
-TIMER2_OC2_SET_ON_CTC
-TIMER2_OC2_CANCELD

-> IF YOU CHOOSE WAVEFORM = WAVEFORM_FASTPWM
OC0_BEHAVIOR Options:
-TIMER2_OC2_CLR_ON_CTC
-TIMER2_OC2_SET_ON_CTC
-TIMER2_OC2_RESERVED
-TIMER2_OC2_CANCELD

-> IF YOU CHOOSE WAVEFORM = WAVEFORM_PWMPHASECORRECT
OC0_BEHAVIOR Options:
-TIMER2_OC2_CLR_ON_CTC
-TIMER2_OC2_SET_ON_CTC
-TIMER2_OC2_RESERVED
-TIMER2_OC2_CANCELD
*/
#define TIMER2_OC2_BEHAVIOR TIMER2_OC2_CANCELD

#else
//
#endif

#endif
