#ifndef ADC_CONFIG_H
#define ADC_CONFIG_H

/* 2 , 4 , 8 , 16 , 32 , 64 , 128 */
#define ADC_PRESCALER_SELECTION ADC_PRESCALER_DIV_BY_64
/* ADC_LEFT_ADJUST , ADC_RIGHT_ADJUST */
#define ADC_ADJUSTMENT ADC_LEFT_ADJUST
/* AVCC , AREF_TURNED_OFF , RESERVED , INTERNAL_3V */
#define ADC_VREF AVCC

#endif